version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: edutech-postgres
    environment:
      POSTGRES_USER: edutech
      POSTGRES_PASSWORD: edutech
      POSTGRES_DB: edutech
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: edutech-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: edutech
      MINIO_ROOT_PASSWORD: edutech12345
    ports:
      - "49000:9000"
      - "49001:9001"
    volumes:
      - minio:/data
volumes:
  pgdata:
  minio:

